package com.almasb.fxglgames.covidfighter;

public enum EntityType {
    PLAYER, PURPLE_ENEMY, RED_ENEMY, WALL, PORTAL, EXIT, LASER_BEAM, RIGHT_ARROW, LEFT_ARROW, DOWN_ARROW, UP_ARROW,
    DRAGON, RIGHT_FIREBALL, LEFT_FIREBALL, DOWN_FIREBALL, UP_FIREBALL, LEFT_BULLET, RIGHT_BULLET, UP_BULLET,
    DOWN_BULLET, RIGHT_VACCINE, LEFT_VACCINE, DOWN_VACCINE, UP_VACCINE, RED_PURPLE
}
